import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,
  users: defineTable({
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()),
    phone: v.optional(v.string()),
    phoneVerificationTime: v.optional(v.number()),
    isAnonymous: v.optional(v.boolean()),
    role: v.optional(v.union(v.literal("owner"), v.literal("manager"), v.literal("cashier"), v.literal("kitchen"))),
    active: v.optional(v.boolean()),
  }).index("email", ["email"]).index("phone", ["phone"]),
  staffPins: defineTable({
    userId: v.id("users"),
    phone: v.string(),
    pinHash: v.string(),
    recoveryPinHash: v.optional(v.string()),
    active: v.boolean(),
  }).index("by_phone", ["phone"]).index("by_userId", ["userId"]),
  pinAttempts: defineTable({
    phone: v.string(),
    attempts: v.number(),
    windowStartedAt: v.number(),
  }).index("by_phone", ["phone"]),
  menuCategories: defineTable({
    name: v.string(),
    slug: v.string(),
    sortOrder: v.number(),
    active: v.boolean(),
  }).index("by_active_and_sortOrder", ["active", "sortOrder"]).index("by_slug", ["slug"]),
  menuItems: defineTable({
    key: v.optional(v.string()),
    name: v.string(),
    description: v.optional(v.string()),
    category: v.string(),
    priceKobo: v.number(),
    icon: v.optional(v.string()),
    color: v.optional(v.string()),
    sortOrder: v.optional(v.number()),
    active: v.boolean(),
    soldOut: v.optional(v.boolean()),
  }).index("by_active", ["active"]).index("by_key", ["key"]).index("by_category", ["category"]),
  orders: defineTable({
    number: v.string(),
    status: v.union(v.literal("new"), v.literal("preparing"), v.literal("ready"), v.literal("completed"), v.literal("cancelled"), v.literal("paid")),
    clientRequestId: v.optional(v.string()),
    paymentStatus: v.optional(v.union(v.literal("unpaid"), v.literal("paid"), v.literal("refunded"))),
    orderType: v.union(v.literal("dine-in"), v.literal("takeaway")),
    items: v.array(v.object({
      key: v.string(),
      name: v.string(),
      quantity: v.number(),
      unitPriceKobo: v.number(),
    })),
    deliveryFeeKobo: v.number(),
    packagingFeeKobo: v.number(),
    totalKobo: v.number(),
    paymentMethod: v.optional(v.union(v.literal("cash"), v.literal("card"), v.literal("transfer"))),
    amountTenderedKobo: v.optional(v.number()),
    changeKobo: v.optional(v.number()),
    foodCostKobo: v.optional(v.number()),
    paidAt: v.optional(v.number()),
    preparingAt: v.optional(v.number()),
    readyAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    cancelledAt: v.optional(v.number()),
    cancellationInventoryHandling: v.optional(v.union(v.literal("return"), v.literal("waste"))),
    createdAt: v.number(),
  }).index("by_status", ["status"]).index("by_payment_status", ["paymentStatus"]).index("by_clientRequestId", ["clientRequestId"]).index("by_createdAt", ["createdAt"]),
  shifts: defineTable({
    status: v.union(v.literal("open"), v.literal("closed")),
    openingCashKobo: v.number(),
    expectedCashKobo: v.number(),
    countedCashKobo: v.optional(v.number()),
    differenceKobo: v.optional(v.number()),
    note: v.optional(v.string()),
    closedBy: v.optional(v.id("users")),
    openedAt: v.number(),
    closedAt: v.optional(v.number()),
  }).index("by_status", ["status"]).index("by_openedAt", ["openedAt"]),
  payments: defineTable({
    orderId: v.id("orders"),
    shiftId: v.optional(v.id("shifts")),
    method: v.union(v.literal("cash"), v.literal("card"), v.literal("transfer")),
    amountKobo: v.number(),
    amountTenderedKobo: v.number(),
    changeKobo: v.number(),
    createdAt: v.number(),
  }).index("by_orderId", ["orderId"]).index("by_shiftId", ["shiftId"]).index("by_createdAt", ["createdAt"]),
  refunds: defineTable({
    orderId: v.id("orders"),
    amountKobo: v.number(),
    method: v.optional(v.union(v.literal("cash"), v.literal("card"), v.literal("transfer"))),
    shiftId: v.optional(v.id("shifts")),
    reason: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_orderId", ["orderId"]).index("by_createdAt", ["createdAt"]).index("by_shiftId", ["shiftId"]),
  ingredients: defineTable({
    name: v.string(),
    unit: v.string(),
    quantity: v.number(),
    lowStockLevel: v.number(),
    costPerUnitKobo: v.optional(v.number()),
    active: v.optional(v.boolean()),
  }).index("by_name", ["name"]),
  recipes: defineTable({
    menuItemId: v.id("menuItems"),
    ingredientId: v.id("ingredients"),
    quantity: v.number(),
  }).index("by_menuItemId", ["menuItemId"]).index("by_ingredientId", ["ingredientId"]),
  inventoryMovements: defineTable({
    ingredientId: v.id("ingredients"),
    type: v.union(v.literal("sale"), v.literal("receive"), v.literal("waste"), v.literal("adjustment"), v.literal("cancellation")),
    quantityDelta: v.number(),
    balanceAfter: v.number(),
    orderId: v.optional(v.id("orders")),
    note: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_ingredientId_and_createdAt", ["ingredientId", "createdAt"]).index("by_createdAt", ["createdAt"]).index("by_orderId", ["orderId"]),
  expenses: defineTable({
    description: v.string(),
    type: v.optional(v.string()),
    amountKobo: v.number(),
    paymentMethod: v.optional(v.union(v.literal("cash"), v.literal("card"), v.literal("transfer"))),
    shiftId: v.optional(v.id("shifts")),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]).index("by_shiftId", ["shiftId"]),
  expenseTypes: defineTable({
    name: v.string(),
    active: v.boolean(),
  }).index("by_name", ["name"]).index("by_active", ["active"]),
  purchases: defineTable({
    supplier: v.optional(v.string()),
    totalKobo: v.number(),
    paymentMethod: v.optional(v.union(v.literal("cash"), v.literal("card"), v.literal("transfer"))),
    shiftId: v.optional(v.id("shifts")),
    note: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]).index("by_shiftId", ["shiftId"]),
  purchaseItems: defineTable({ purchaseId: v.id("purchases"), ingredientId: v.id("ingredients"), quantity: v.number(), unitCostKobo: v.number(), totalKobo: v.number() }).index("by_purchaseId", ["purchaseId"]).index("by_ingredientId", ["ingredientId"]),
});
